name: contacts_app
description: A test assignment for Eleven Systems

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  objectbox_generator: any
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  objectbox: ^2.0.0
  equatable: ^2.0.5 #library is used for checking if the state was changes
  get_it: ^7.2.0 # dependency injection library
  shared_preferences: ^2.0.6 # library is used fot storing flag to db initialisation action
  objectbox_flutter_libs: ^2.0.0
  path: ^1.8.1
  path_provider: ^2.0.11 #library is used for providing a path for objectbox store storing
  go_router: ^7.0.0
  share_plus: ^6.3.4 #library is used for sharing the contact feature
  url_launcher: #lasted version. Library is used for launching an sms send from contact page
  mask_text_input_formatter: ^2.4.0 #library is used for enhancing phone number input
  uuid: ^3.0.7 #library is used for generation unique contact id for case of adding contact feature

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: any # library is used for generating contact objectBox model from the model

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/json/initial_contacts.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
